// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_prueba_software.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Book", b =>
                {
                    b.Property<int>("id_book")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_book"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_book");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id_book = 1,
                            description = "Descripción del libro 1",
                            name = "Libro 1"
                        },
                        new
                        {
                            id_book = 2,
                            description = "Descripción del libro 2",
                            name = "Libro 2"
                        },
                        new
                        {
                            id_book = 3,
                            description = "Descripción del libro 3",
                            name = "Libro 3"
                        },
                        new
                        {
                            id_book = 4,
                            description = "Descripción del libro 4",
                            name = "Libro 4"
                        });
                });

            modelBuilder.Entity("API.Models.Reserve", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_reserve")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Reserves");

                    b.HasData(
                        new
                        {
                            id = 1,
                            book_id = 1,
                            code = 0,
                            date_reserve = new DateTime(2023, 6, 9, 12, 47, 19, 454, DateTimeKind.Local).AddTicks(8228),
                            user_id = 1
                        },
                        new
                        {
                            id = 2,
                            book_id = 2,
                            code = 0,
                            date_reserve = new DateTime(2023, 6, 2, 12, 47, 19, 454, DateTimeKind.Local).AddTicks(8256),
                            user_id = 1
                        },
                        new
                        {
                            id = 3,
                            book_id = 3,
                            code = 0,
                            date_reserve = new DateTime(2023, 5, 26, 12, 47, 19, 454, DateTimeKind.Local).AddTicks(8259),
                            user_id = 2
                        },
                        new
                        {
                            id = 4,
                            book_id = 4,
                            code = 0,
                            date_reserve = new DateTime(2023, 5, 19, 12, 47, 19, 454, DateTimeKind.Local).AddTicks(8261),
                            user_id = 2
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("facultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            facultad = "Facultad 1",
                            name = "Usuario 1"
                        },
                        new
                        {
                            id = 2,
                            facultad = "Facultad 2",
                            name = "Usuario 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
